project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    theme: yeti
    comments:
      hypothesis: true
  #docx: default
  #jats: default
  #pdf: default

execute:
  freeze: true
